---
ID: "8a63b9a6-fd3c-4e02-a02b-8489336e2c0e"
Parent: "773fe508-19cc-4a2f-b1ea-e2606ecfc967"
Template: "773fe508-19cc-4a2f-b1ea-e2606ecfc967"
Path: /sitecore/templates/Project/MDigital/Content Types/Navigation/Navigation Settings/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{61243AF8-A0BD-4D1C-AB0D-29E59E8357DE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211005T185212Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb24de95-b557-4fc6-946f-ae6ca2b28cff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211005T185224Z
