---
ID: "e14913e4-f203-4c7e-b7c8-91d7140ad7aa"
Parent: "4b3aa55f-3288-41ac-a1f2-3938f25faa6d"
Template: "4b3aa55f-3288-41ac-a1f2-3938f25faa6d"
Path: /sitecore/templates/Project/MDigital/Content Types/Navigation/Tertiary Navigation Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211005T190029Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33dd3268-a63a-4965-bcb1-0eb16ceba318"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211005T190033Z
    - ID: "e52bb558-7157-4539-b7e7-78466eac4dcb"
      Hint: LinkText
      Value: $name
