---
ID: "7a66bba7-6b7d-4d76-9a72-b6dacfd65ebb"
Parent: "95c2152b-1ae7-4a5a-9129-cc72a98dcac2"
Template: "95c2152b-1ae7-4a5a-9129-cc72a98dcac2"
Path: /sitecore/templates/Project/MDigital/Content Types/Navigation/Secondary Navigation Item/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4B3AA55F-3288-41AC-A1F2-3938F25FAA6D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211005T184539Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "043d9cc9-71ed-4665-b418-20c97e5e0d75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211005T190039Z
    - ID: "e52bb558-7157-4539-b7e7-78466eac4dcb"
      Hint: LinkText
      Value: $name
